controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute
#app_upload_file:
#    path: /upload-file
#    controller: App\Controller\AudioController::handleFileUpload